title: SHumphreys Blog
description: Ideas in tech and music.
author: 
  name: "Scott Humphreys"
  email: 

# GitHub older version:
#theme: minima
# or use latest version:
remote_theme: jekyll/minima

# Minima social links
email:
twitter_username:
github_username: shumphreys2
rss: 

url: https://shumphreys2.github.io
base_url: /shumphreys2.github.io 
repository: shumphreys2/shumphreys2.github.io 

permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: classic
  # Generate social links in footer. Updated for Jekyll v3
  social_links:
    - title: SHumphreys2 repository at GitHub
      icon: github
      url: "https://github.com/shumphreys2/"
  #social_links:
  #  - { platform: github, user_url: "https://github.com/shumphreys2/" }

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  #- _pages/about.md
  #- _pages/archive.md

include:
    - _pages

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

