title: SHumphreys2 Blog
description: A blog on ideas in tech and music.

theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Minima: show excerpts in the frontpage
show_excerpts: true

exclude: [vendor]

#exclude: 
#    - .gitignore
#    - Gemfile
#    - Gemfile.lock
#    - LICENSE
#    - README.md
