title: SHumphreys2 Blog
description: A blog on ideas in tech and music.

theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  #- _pages/about.md
  #- _pages/archive.md

include:
    - _pages

exclude: [vendor]

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
